name: PlatformIO CI

on: [push, pull_request]

jobs:

  test-and-analyze:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cmd: ["test", "check"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Configure git
      run: git config --global advice.detachedHead false

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run platform.io
      run: platformio ${{ matrix.cmd }} -v
